version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=ap-south-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  etl:
    build: .
    image: etl
    container_name: etl_container
    depends_on:
      - interview-localstack
    ports:
      - "4444:4444"
    command: sh -c "sleep infinity"

